modLoader="javafml"
loaderVersion="[28,)"

[[mods]]
modId="realismmod"
version="1.0.0"
displayName="REALISM_MOD"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Пользователь, MCreator"

[[dependencies.realismmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"



